# Site settings
title: Portal CMP
email: marcelomogami@gmail.com
url: http://www.portalcmp.com.br
description: "Portal de serviços do Condomínio Morada do Parque"
skills: "Condomínio Morada do Parque"
#meta_author: LastName FirstName

# Google webmaster tools
google_verify:

# https://ssl.bing.com/webmaster/configure/verify/ownership Option 2 content= goes here
bing_verify:

# Contact form:
# - static : pass through formspree.io to validate email sending
# - disqus : replace contact form by disqus thread
# - comment the line below if you want to stick with the default PHP contact form
# contact: static

# If you use disqus you need disqus shortname
# https://help.disqus.com/customer/portal/articles/466208
disqus_shortname:

# Color settings (hex-codes without the leading hash-tag)
color:
  primary: ffdd70 #18bc9c #80B3FF
  primary-rgb: "255,221,112" #"24,288,156" #"128,179,255"
  secondary: 424f57 #2c3e50 #FD6E8A
  secondary-dark: 3c4c59 #233140 #A2122F

# Footer settings
footer:
  copyright: Adriana e Marcelo Mogami
  location: Condomínio Morada do Parque
  social:
  credits: Anuncie Aqui

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: twitter
    url: http://twitter.com/celo

# Postal address (add as many lines as necessary)
address:
  - line: Avenida Brasil, 269
  - line: Cuiabá - MT - 78055-508

# Credits content
credits: '<a href="#contact">Entre em contato conosco</a>'

# Build settings
markdown: kramdown
permalink: pretty
